/* this file automatically generated by Makefile */
#include "lib.h"
#include "dict.h"
#include "dict-sql.h"
void dict_drivers_register_all(void) {
dict_drivers_register_builtin();
dict_sql_register();
}
void dict_drivers_unregister_all(void) {
dict_drivers_unregister_builtin();
dict_sql_unregister();
}
